name: 'Madlib Publish'
description: 'Checkout a Madlib project and build a release'
inputs:
  version:
    description: 'Specify a version to publish, e.g. "v0.0.1"'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 😈 Checking out Madlib repo...
      uses: actions/checkout@v4
    - name: ⚙️  Installing node...
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: 👛 Generating changelog..
      id: changelog
      uses: TriPSs/conventional-changelog-action@v5.2.1
      with:
        presets: "conventionalcommits"
        github-token: ${{ github.token }}
        skip-on-empty: false
        tag-prefix: 'v'
        skip-commit: true
        skip-version-file: true
    - name: 🪓 Deleting created tag from changelog...
      shell: bash
      run: |
        git push --delete origin v${{ steps.changelog.outputs.version }}
        git tag -d v${{ steps.changelog.outputs.version }}
    - name: 📦 Creating release...
      id: create_release
      uses: softprops/action-gh-release@v2.0.5
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: Release ${{ github.event.inputs.version }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
        draft: false
        prerelease: false
